Feat/#42/2fa verify email action
Femlives/gfnmjwft pull request #64
Opened 2024-11-21 09:05 UTC by daryafurman

2024-11-21 10:02 UTC, SimonSchoetz requested changes

2024-11-21 10:02 UTC, SimonSchoetz commented on src/util/encryption/encrypt-passwords.ts
Please write tests to make sure all the edge cases you thought about are not lost if somebody is refactoring this in the future :)

2024-11-25 08:24 UTC, Femlives commented on src/util/encryption/encrypt-password.test.ts
> +    expect(encryptPassword(noString)).rejects.toThrow();
you sure these tests do what you think they do? `encryptPassword` is an async function but I see no async/await declarations

2024-12-02 10:38 UTC, SimonSchoetz approved these changes

2024-12-02 10:38 UTC, merged