Feat/#49/update button component
Femlives/gfnmjwft pull request #70
Opened 2024-11-21 12:48 UTC by daryafurman

![Знімок екрана 2024-11-21 134826](https://github.com/user-attachments/assets/97e5b6d9-fda5-4f7f-ac38-d09041d6ac71)

2024-11-21 17:07 UTC, Femlives commented on src/components/Button/Button.tsx
This could be more maintainable and readable. Imagine when a new color or even a new style variant for all colors is needed and we always have to add that to the `variant` type and how long and error-prone the  `const variantStyles` becomes with each addon.

2024-11-21 17:08 UTC, Femlives commented on src/components/Button/Button.tsx
> +  const pinkHoverStyles = `hover:bg-[#FE83CF]`;
what about blue over styles? Or even green ones?

2024-11-21 17:08 UTC, Femlives commented on src/components/Button/Button.tsx
> +        : pinkOutlinedStyles;
chained ternary operators make my eyes itch 😄

2024-11-21 17:17 UTC, Femlives commented on src/app/globals.css
> +  --text-primary: #24091a;
not really a fan of the `text` prefix since it is also a key for tailwind, as you already used it in line 24 in the Button.tsx file. My suggestion would be to call it `pink-dark` and also switch `light-pink-secondary` to `pink-secondary-light`or something like that. We should discuss the system ( [colorname]-[spec 1]-[spec 2] )

2024-11-21 17:17 UTC, Femlives requested changes
.

2024-11-22 08:13 UTC, daryafurman commented on src/components/Button/Button.tsx
> +  const pinkHoverStyles = `hover:bg-[#FE83CF]`;
It will be in issue #50 😊

2024-11-22 09:02 UTC, daryafurman commented
@SimonSchoetz @Femlives  I updated code😊

2024-11-25 08:25 UTC, Femlives commented on src/components/Button/Button.tsx
>  };
yesss I like that a lot more!

2024-11-25 08:26 UTC, Femlives commented on src/components/Button/Button.tsx
> +  variant?: 'pink-filled' | 'blue-filled' | 'pink-outlined';
Can't this be typed differently so we don't have to maintain it everytime we add a new color to the config?

2024-11-25 10:41 UTC, Femlives commented on src/components/Button/Button.tsx
> +  const baseStyles = `py-2 px-4 rounded-lg w-full font-semibold transition-colors`;
we already have 2 Designs with different heights. How should we handle dimensions in the future?

2024-11-25 13:34 UTC, merged