Feat/#63/footer section
Femlives/gfnmjwft pull request #84
Opened 2024-11-28 13:03 UTC by daryafurman

## Checklist

- [ ] 🙅‍♀️ No leftover console.logs
- [ ] 🦾 Sufficient tests, e. g. unit test
- [ ] 🫶 Documentation updated where necessary
- [ ] 🧠 Left over TODOs are marked with a url to the ticket

closes #63

2024-11-28 13:30 UTC, SimonSchoetz commented on src/components/Footer.tsx
> +      <Image src={logo} alt="Femlives Logo" width={179} height={30.4} className="mb-4" />
Where are these numbers coming from? :)

2024-11-28 13:38 UTC, SimonSchoetz requested changes

2024-11-28 13:38 UTC, SimonSchoetz commented on src/components/Footer.tsx
> +      <Image src={logo} alt="Femlives Logo" width={179} height={30.4} className="mb-4" />
- check out the `flex-center` class I made in the `global.css` (because we will need this everywhere)
- you added `gap` to the `footer` and also margin to the image. Do you need both?

2024-11-28 13:38 UTC, SimonSchoetz commented on src/components/Footer.tsx
> +      <Image src={logo} alt="Femlives Logo" width={179} height={30.4} className="mb-4" />
Where are these numbers coming from and how do they help? :)

2024-11-28 13:38 UTC, SimonSchoetz commented on src/components/Footer.tsx
> +          </li>
looks like a lot of duplicated code to me :)

2024-11-28 13:38 UTC, SimonSchoetz commented on src/components/Footer.tsx
> -      <AppLink label={'Imprint'} internalRoute={Route.IMPRINT} />
Is the Applink component not sufficient for the new Footer component

2024-11-28 14:07 UTC, SimonSchoetz commented on src/components/Footer.tsx
> +        <ul className="flex items-start gap-[90px] text-lg text-black font-bold">
let's stick with tailwind numbers intsead of setting own ones :) (talking about the gap value)

2024-12-02 09:27 UTC, Femlives requested changes

2024-12-02 09:27 UTC, Femlives commented on src/enums/routes.ts
> +  PRIVACY_POLICY = '/privacy_policy',
please fix all the typos and inconsistencies 
and I think it's an unspoken convention to name these route just 'about' or just 'contact' :D

2024-12-02 09:27 UTC, Femlives commented on src/components/Footer.tsx
> +          </li>
I commented earlier, that this is quite a lot duplicated code rather: A pattern that looks pretty clear to me, that we could use a loop or mapping method to generate the structure for us. You can have a look at other sections I added for inspiration

2024-12-02 09:27 UTC, Femlives commented on src/components/Footer.tsx
> +export default Footer;
not really part of this PR but I did a little research about different types of exports and I found that while this `export default` makes good sense for `page.tsx` files, it's not really helpful for components. I'd like to have the components exported like any other function, as I did it with the newer sections, too. So we can use a barell file without problem and have a cleaner import structure within our files

2024-12-02 13:45 UTC, daryafurman commented on src/components/Footer.tsx
> +          </li>
The interesting part is that I´ve done refactoring, but then decided to change😔 
maybe because I forgot about AppLink  and then there were some errors, so I went back, but I fixed it now

2024-12-03 10:38 UTC, SimonSchoetz approved these changes

2024-12-03 10:38 UTC, Femlives approved these changes

2024-12-03 10:39 UTC, merged